name: Audit

on:
  pull_request:
    branches:
      - next
      - latest

  push:
    branches:
      - next
      - latest

jobs:
  tests:
    name: Check that the dependencies do not introduce vulnerabilities in the project
    runs-on: ubuntu-20.04 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Audit
        run: docker-compose run --rm --user root -T npm audit
