name: Code Style

on:
  pull_request:
    branches:
      - next
      - latest

  push:
    branches:
      - next
      - latest

jobs:
  tests:
    name: Check that the code style is consistently applied to sources
    runs-on: ubuntu-20.04 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installation
        run: docker-compose run --rm --user root -T npm install

      - name: Lint
        run: docker-compose run --rm --user root -T npm run lint
